#!/bin/bash -ex
crew files $(basename "$0") | grep /usr/local/bin | xargs --no-run-if-empty -I % sh -c 'echo "testing %" ; % --help 2>&1 ; exitcode=$?  ; echo "exitcode for % is ${exitcode}" ; [[ ${exitcode} != '1' ]] && exit 0 || exit 1'
