{
  "Nano": {
    "id": 0,
    "name": "Nano",
    "url": "https://www.nano-editor.org",
    "description": "Nano, GNU nano is designed to be a free replacement for the Pico text editor.",
    "background": "",
    "category": "Text Editors",
    "themecolor": "#E6E6FA",
    "author": "Gnu Nano",
    "icon": "https://d2.alternativeto.net/dist/icons/nano_87840.png?width=128&height=128&mode=crop&upscale=false",
     "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  },
  "libreoffice": {
    "id": 1,
    "name": "Libre Office",
    "url": "https://www.libreoffice.org/",
    "description": "Editor Suite",
    "background": "",
    "category": "Word Proccescing",
    "themecolor": "",
    "author": "Mozilla",
    "icon": "https://softlay.net/wp-content/uploads/2015/09/libreoffice-Logo-Icon-200x200.png",
    "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  },
  "gimp": {
    "id": 2,
    "name": "GIMP",
    "url": "https://www.gimp.org",
    "description": "GNU Image Manipulation Program",
    "background": "",
    "category": "Image Editors",
    "themecolor": "",
    "author": "GNU",
    "icon": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/The_GIMP_icon_-_gnome.svg/1024px-The_GIMP_icon_-_gnome.svg.png",
    "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  },
  "aIDE": {
    "id": 3,
    "name": "Arduino IDE",
    "url": "ardunio.cc",
    "description": "Program your Arduino",
    "background": "",
    "category": "IDE's",
    "themecolor": "#2DBE5F",
    "author": "Arduino-GNU",
    "icon": "https://i2.wp.com/www.mac-torrent-download.net/wp-content/uploads/2016/05/arduino_uno_ide_icon.jpg?resize=175%2C175",
    "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  },
  "code": {
    "id": 4,
    "name": "Visual Studio Code",
    "url": "https://code.visualstudio.com/",
    "description": "Vscoder",
    "background": "",
    "category": "Code Ide",
    "themecolor": "#fff",
    "author": "Microsoft",
    "icon": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Visual_Studio_Code_1.18_icon.svg/1028px-Visual_Studio_Code_1.18_icon.svg.png",
    "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  },
  "ink": {
    "id": 5,
    "name": "Inkscape GNU",
    "url": "https://inkscape.org",
    "description": "Vector Editor",
    "background": "",
    "category": "Vector Editor",
    "themecolor": "#fff",
    "author": "GNU",
    "icon": "https://vignette.wikia.nocookie.net/en.linux/images/5/5e/Inkscape-logo.png/revision/latest?cb=20130927154855",
    "stars": 50,
    "5stars": 30,
    "4stars": 10,
    "3stars": 5,
    "2stars": 8,
    "1stars": 2
  }
}
