language: bash
services:
  - docker

before_install:
  - docker pull brunux/chromeos

script:
  # Workaround sudo prompting for password by editing existing chronos entry
  - docker run -it
               -v $PWD:/travis
               brunux/chromeos
               /bin/sh -c "
      grep chronos /etc/sudoers > /tmp/sudoers.new;
      sed s/chronos/ALL/ /tmp/sudoers.new > /etc/sudoers;
      sudo -u chronos bash /travis/install.sh;
    "
