#!/usr/bin/env ruby

require_relative '../lib/const'
require_relative '../lib/color'

def get_buildsystems(file, field)
  return `grep ^class #{file} | cut -d' ' -f#{field} | xargs`.chomp
end

def check_buildsystem(name, verbose: false)
  puts "Checking #{name} package ...".yellow if verbose
  buildsystem = get_buildsystems(File.join(CREW_PACKAGES_PATH, "#{name}.rb"), 4)

  buildsystems = "Package #{get_buildsystems("#{CREW_LIB_PATH}/lib/buildsystems/*.rb", 2)}".split
  if buildsystems.include?(buildsystem)
    puts "Buildsystem test for #{name} passed.".lightgreen if verbose
    return 0
  else
    puts "#{buildsystem} is an invalid buildsystem. Valid buildsystems include #{buildsystems.sort.join(', ')}.".lightred
    puts "Buildsystem test for #{name} failed.".lightred
    return 1
  end
end

if ARGV[0]
  ARGV.each do |name|
    if File.file?(File.join(CREW_PACKAGES_PATH, "#{name}.rb"))
      check_buildsystem(name, verbose: true)
    else
      puts "Package #{name} not found.".lightred
    end
  end
else
  failed_packages = 0
  Dir["#{CREW_PACKAGES_PATH}/*.rb"].each do |filename|
    failed_packages += check_buildsystem(File.basename(filename, '.rb'))
  end

  if failed_packages.positive?
    puts "\n#{failed_packages} packages failed buildsystem tests.".lightred
    exit(1)
  else
    puts "\nAll packages passed buildsystem tests.".lightgreen
  end
end
