#!/usr/bin/env ruby

require_relative '../lib/const'
require_relative '../lib/color'
require_relative '../lib/package'

# Add >LOCAL< lib to LOAD_PATH so that packages can be loaded
$LOAD_PATH.unshift File.join(CREW_LIB_PATH, 'lib')

def check_properties(pkg, verbose: false)
  puts "Checking #{pkg.name} package ...".yellow if verbose
  puts "#{pkg.name} is missing a description.".lightred if pkg.description.to_s.empty?
  puts "#{pkg.name} is missing a homepage.".lightred if pkg.homepage.to_s.empty?
  puts "#{pkg.name} is missing a version.".lightred if pkg.version.to_s.empty?
  puts "#{pkg.name} is missing a license.".lightred if pkg.license.to_s.empty?
  puts "#{pkg.name} is missing a compatibility.".lightred if pkg.compatibility.to_s.empty?
  if pkg.description.to_s.empty? || pkg.homepage.to_s.empty? || pkg.version.to_s.empty? || pkg.license.to_s.empty? || pkg.compatibility.to_s.empty?
    puts "Property tests for #{pkg.name} failed.".lightred
    return 1
  else
    puts "Property tests for #{pkg.name} passed.".lightgreen if verbose
    return 0
  end
end

if ARGV[0]
  ARGV.each do |name|
    if File.file?(File.join(CREW_PACKAGES_PATH, "#{name}.rb"))
      check_properties(Package.load_package(File.join(CREW_PACKAGES_PATH, "#{name}.rb")), verbose: true)
    else
      puts "Package #{name} not found.".lightred
    end
  end
else
  failed_packages = 0
  Dir["#{CREW_PACKAGES_PATH}/*.rb"].each do |filename|
    failed_packages += check_properties(Package.load_package(filename))
  end

  if failed_packages.positive?
    puts "\n#{failed_packages} packages failed property tests.".lightred
    exit(1)
  else
    puts "\nAll packages passed property tests.".lightgreen
  end
end
