#!/usr/bin/env ruby

# This test checks for spelling errors and provides suggested changes.

require_relative '../lib/const'
require_relative '../lib/color'

puts "This test requires codespell.  Install with 'pip install codespell'.".lightred unless File.exist? "#{CREW_PREFIX}/bin/codespell"

# Check for spelling errors.
Dir.chdir '../' do
  system 'codespell'
end
