#!/usr/bin/env ruby

require 'find'
require_relative '../lib/const'
require_relative '../lib/color'

CUR_DIR = File.dirname(__FILE__)

# Add >LOCAL< lib to LOAD_PATH
$LOAD_PATH.unshift "#{CUR_DIR}/../lib"

puts "Running tests..."

Find.find(CUR_DIR) do |filename|
  if File.extname(filename) == '.rb'
    puts "\nTest Name: #{File.basename(filename, ".rb")}"
    load filename
  end
end

puts "\nAll tests successful.".lightgreen
