#!/bin/bash -ex
for b in $(crew files ruby | grep /usr/local/bin); do $b --version 2>&1; done
# See https://bugs.ruby-lang.org/issues/21607
ruby -e "require 'concurrent-ruby' ; puts 'success'"
# See https://bugs.ruby-lang.org/issues/20085
ruby -e "Fiber.new{}.resume"
