require 'package'

class Azure_cli < Package
  description 'The Azure CLI 2.0 is Azure\'s new command-line experience for managing Azure resources.'
  homepage 'https://github.com/Azure/azure-cli'
  version '2.21.0'
  license 'MIT'
  compatibility 'i686,x86_64'
  source_url 'https://github.com/Azure/azure-cli/archive/azure-cli-2.21.0.tar.gz'
  source_sha256 'bbe4a1f85418d239444717f2c9706a87f81fd2515bb0bb4b4e48548fd3e08caa'

  depends_on 'py3_azure_mgmt_imagebuilder'
  depends_on 'py3_azure_mgmt_resource'
  depends_on 'py3_azure_mgmt_recoveryservicesbackup'
  depends_on 'py3_azure_mgmt_eventgrid'
  depends_on 'py3_azure_mgmt_managedservices'
  depends_on 'py3_azure_mgmt_signalr'
  depends_on 'py3_azure_mgmt_sqlvirtualmachine'
  depends_on 'py3_azure_mgmt_eventhub'
  depends_on 'py3_azure_mgmt_maps'
  depends_on 'py3_azure_mgmt_consumption'
  depends_on 'py3_azure_mgmt_datamigration'
  depends_on 'py3_azure_mgmt_cosmosdb'
  depends_on 'py3_azure_mgmt_iothub'
  depends_on 'py3_azure_mgmt_security'
  depends_on 'py3_azure_mgmt_cognitiveservices'
  depends_on 'py3_azure_synapse_spark'
  depends_on 'py3_azure_mgmt_containerinstance'
  depends_on 'py3_azure_mgmt_appconfiguration'
  depends_on 'py3_azure_mgmt_containerregistry'
  depends_on 'py3_azure_mgmt_advisor'
  depends_on 'py3_azure_functions_devops_build'
  depends_on 'py3_azure_mgmt_keyvault'
  depends_on 'py3_azure_mgmt_loganalytics'
  depends_on 'py3_azure_mgmt_reservations'
  depends_on 'py3_azure_mgmt_cdn'
  depends_on 'py3_azure_mgmt_servicefabric'
  depends_on 'py3_azure_mgmt_billing'
  depends_on 'py3_azure_mgmt_network'
  depends_on 'py3_azure_cli_core'
  depends_on 'py3_azure_mgmt_media'
  depends_on 'py3_azure_mgmt_privatedns'
  depends_on 'py3_azure_keyvault'
  depends_on 'py3_azure_mgmt_servicebus'
  depends_on 'py3_azure_synapse_artifacts'
  depends_on 'py3_azure_mgmt_managementgroups'
  depends_on 'py3_azure_mgmt_iotcentral'
  depends_on 'py3_azure_mgmt_sql'
  depends_on 'py3_azure_mgmt_databoxedge'
  depends_on 'py3_azure_mgmt_netapp'
  depends_on 'py3_azure_mgmt_datalake_store'
  depends_on 'py3_azure_mgmt_iothubprovisioningservices'
  depends_on 'py3_azure_keyvault_administration'
  depends_on 'py3_azure_mgmt_trafficmanager'
  depends_on 'py3_azure_appconfiguration'
  depends_on 'py3_azure_mgmt_recoveryservices'
  depends_on 'py3_azure_mgmt_applicationinsights'
  depends_on 'py3_azure_mgmt_storage'
  depends_on 'py3_azure_mgmt_monitor'
  depends_on 'py3_azure_mgmt_apimanagement'
  depends_on 'py3_azure_mgmt_relay'
  depends_on 'py3_azure_graphrbac'
  depends_on 'py3_azure_mgmt_msi'
  depends_on 'py3_azure_mgmt_compute'
  depends_on 'py3_azure_mgmt_redis'
  depends_on 'py3_azure_mgmt_botservice'
  depends_on 'py3_azure_mgmt_rdbms'
  depends_on 'py3_azure_mgmt_containerservice'
  depends_on 'py3_azure_mgmt_policyinsights'
  depends_on 'py3_azure_cosmos'
  depends_on 'py3_azure_mgmt_redhatopenshift'
  depends_on 'py3_azure_mgmt_web'
  depends_on 'py3_azure_storage_common'
  depends_on 'py3_azure_mgmt_batch'
  depends_on 'py3_azure_mgmt_batchai'
  depends_on 'py3_azure_multiapi_storage'
  depends_on 'py3_azure_mgmt_synapse'
  depends_on 'py3_azure_identity'
  depends_on 'py3_azure_mgmt_authorization'
  depends_on 'py3_azure_mgmt_dns'
  depends_on 'py3_azure_mgmt_datalake_analytics'
  depends_on 'py3_azure_batch'
  depends_on 'py3_azure_datalake_store'
  depends_on 'py3_azure_loganalytics'
  depends_on 'py3_azure_mgmt_deploymentmanager'
  depends_on 'py3_azure_mgmt_devtestlabs'
  depends_on 'py3_azure_mgmt_kusto'
  depends_on 'py3_azure_mgmt_hdinsight'
  depends_on 'py3_azure_mgmt_search'
  depends_on 'py3_azure_mgmt_marketplaceordering'
  depends_on 'py3_azure_synapse_accesscontrol'
  depends_on 'py3_antlr4_python3_runtime'
  depends_on 'py3_javaproperties'
  depends_on 'py3_jsmin'
  depends_on 'py3_scp'
  depends_on 'py3_urllib3'
  depends_on 'py3_jsondiff'
  depends_on 'py3_websocket_client'
  depends_on 'py3_sshtunnel'
  depends_on 'py3_xmltodict'
  depends_on 'py3_fabric'
  depends_on 'py3_vsts_cd_manager'
  depends_on 'py3_semver'
  depends_on 'py3_pytz'
  depends_on 'py3_setuptools' => :build

  def self.build
    system "python3 setup.py build #{CREW_SETUP_PY3_BUILD_OPTIONS}"
  end

  def self.install
    system "python3 setup.py install #{CREW_SETUP_PY_INSTALL_OPTIONS}"

    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/etc/bash.d/"
    @azurebashd = <<~AZUREEOF
      # Microsoft Azure CLI bash completion
      source #{CREW_PREFIX}/share/azure-cli/az.completion
    AZUREEOF
    IO.write("#{CREW_DEST_PREFIX}/etc/bash.d/az", @azurebashd)
  end
end
