require 'buildsystems/autotools'

class Bochs < Autotools
  description 'Bochs is a highly portable open source IA-32 (x86) PC emulator written in C++, that runs on most popular platforms.'
  homepage 'https://bochs.sourceforge.io/'
  version '3.0'
  license 'LGPL-3'
  compatibility 'aarch64 armv7l x86_64'
  source_url "https://downloads.sourceforge.net/project/bochs/bochs/#{version}/bochs-#{version}.tar.gz"
  source_sha256 'cb6f542b51f35a2cc9206b2a980db5602b7cd1b7cf2e4ed4f116acd5507781aa'
  binary_compression 'tar.zst'

  binary_sha256({
    aarch64: 'b99fcc602945a7565c43cef990825a24efbd8bc56cc9a4587b20dc57c4952781',
     armv7l: 'b99fcc602945a7565c43cef990825a24efbd8bc56cc9a4587b20dc57c4952781',
     x86_64: '4efe1ba27d194e39743684c759038b6ee9007bb5cdd504d7ac596faecc224e14'
  })

  depends_on 'acpica' => :executable if ARCH.eql?('x86_64')
  depends_on 'gcc_lib' => :executable
  depends_on 'glibc' => :executable
  depends_on 'glibc_lib' => :executable
  depends_on 'libbsd' => :executable
  depends_on 'libx11' => :executable
  depends_on 'libxau' => :executable
  depends_on 'libxcb' => :executable
  depends_on 'libxdmcp' => :executable
  depends_on 'libxpm' => :executable
  depends_on 'libxrandr' => :executable

  autotools_build_extras do
    File.write '.bochsrc', <<~EOF
      # configuration file generated by Bochs
      plugin_ctrl: unmapped=true, biosdev=true, speaker=true, extfpuirq=true, parallel=true, serial=true
      config_interface: textconfig
      display_library: x
      memory: guest=32, host=32, block_size=128
      romimage: file="/usr/local/share/bochs/BIOS-bochs-latest", address=0x00000000, options=none, flash_data=none
      vgaromimage: file="/usr/local/share/bochs/VGABIOS-lgpl-latest.bin"
      boot: floppy
      floppy_bootsig_check: disabled=0
      floppya: type=1_44
      # no floppyb
      ata0: enabled=true, ioaddr1=0x1f0, ioaddr2=0x3f0, irq=14
      ata0-master: type=none
      ata0-slave: type=none
      ata1: enabled=true, ioaddr1=0x170, ioaddr2=0x370, irq=15
      ata1-master: type=none
      ata1-slave: type=none
      ata2: enabled=false
      ata3: enabled=false
      optromimage1: file=none
      optromimage2: file=none
      optromimage3: file=none
      optromimage4: file=none
      optramimage1: file=none
      optramimage2: file=none
      optramimage3: file=none
      optramimage4: file=none
      pci: enabled=1, chipset=i440fx, slot1=none, slot2=none, slot3=none, slot4=none, slot5=none
      vga: extension=vbe, update_freq=10, realtime=1, ddc=builtin, vbe_memsize=16
      cpu: count=1, ips=4000000, model=p4_willamette, reset_on_triple_fault=1, cpuid_limit_winnt=0, ignore_bad_msrs=1, mwait_is_nop=0
      print_timestamps: enabled=0
      port_e9_hack: enabled=false, all_rings=false
      private_colormap: enabled=0
      clock: sync=none, time0=local, rtc_sync=0
      # no cmosimage
      log: -
      logprefix: %t%e%d
      debug: action=ignore
      info: action=report
      error: action=report
      panic: action=ask
      keyboard: type=mf, serial_delay=150, paste_delay=100000, user_shortcut=none
      mouse: type=ps2, enabled=false, toggle=ctrl+mbutton
      speaker: enabled=true, mode=system
      parport1: enabled=true, file=none
      parport2: enabled=false
      com1: enabled=true, mode=null
      com2: enabled=false
      com3: enabled=false
      com4: enabled=false
    EOF
  end

  autotools_install_extras do
    FileUtils.install '.bochsrc', "#{CREW_DEST_HOME}/.bochsrc", mode: 0o644
  end
end
