require 'package'

class Ca_certificates < Package
  description 'Common CA Certificates PEM files'
  homepage 'https://packages.debian.org/sid/ca-certificates'
  version '20260601-0e5c792'
  license 'GPL-2.0-or-later MPL-2.0'
  compatibility 'all'
  source_url 'https://salsa.debian.org/debian/ca-certificates.git'
  git_hashtag '0e5c792b46e3331aedcd27bfa49792abf98c5c76'
  binary_compression 'tar.zst'

  binary_sha256({
    aarch64: '3dfa342b03229090d0afe614fed6b7464f6192eb5c97ce637e5960b1440f3a5a',
     armv7l: '3dfa342b03229090d0afe614fed6b7464f6192eb5c97ce637e5960b1440f3a5a',
       i686: '3b36031d6403f644821725a01899dcbad53b4055a6b710f0a1026b4cb0552f65',
     x86_64: '5e90c4bcab171ce630862f9010d2241f82b00b5765f10d804723836c38836a71'
  })

  depends_on 'py3_cryptography' => :build

  print_source_bashrc

  def self.patch
    # Patch from:
    # https://gitweb.gentoo.org/repo/gentoo.git/plain/app-misc/ca-certificates/files/ca-certificates-20150426-root.patch
    File.write 'ca-certificates-20150426-root.patch', <<~'GENTOO_CA_CERT_HEREDOC'
      --- a/sbin/update-ca-certificates      2025-05-01 00:06:58.282420314 +0800
      +++ b/sbin/update-ca-certificates      2025-05-01 00:07:00.752420448 +0800
      @@ -30,6 +30,8 @@
       CERTBUNDLE=ca-certificates.crt
       ETCCERTSDIR=/etc/ssl/certs
       HOOKSDIR=/etc/ca-certificates/update.d
      +ROOT=""
      +RELPATH=""

       while [ $# -gt 0 ];
       do
      @@ -67,13 +69,25 @@
             LOCALCERTSDIR="$1/${LOCALCERTSDIR}"
             ETCCERTSDIR="$1/${ETCCERTSDIR}"
             HOOKSDIR="$1/${HOOKSDIR}";;
      +    --root|-r)
      +      shift
      +      # Needed as c_rehash wants to read the files directly.
      +      # This gets us from $CERTSCONF to $CERTSDIR.
      +      RELPATH="../../.."
      +      ROOT=$(readlink -f "$1");;
           --help|-h|*)
      -      echo "$0: [--verbose] [--fresh]"
      +      echo "$0: [--verbose] [--fresh] [--root <dir>]"
             exit;;
         esac
         shift
       done

      +CERTSCONF="$ROOT$CERTSCONF"
      +CERTSDIR="$ROOT$CERTSDIR"
      +LOCALCERTSDIR="$ROOT$LOCALCERTSDIR"
      +ETCCERTSDIR="$ROOT$ETCCERTSDIR"
      +HOOKSDIR="$ROOT$HOOKSDIR"
      +
       if [ ! -s "$CERTSCONF" ]
       then
         fresh=1
      @@ -102,7 +116,7 @@
                                                         -e 's/,/_/g').pem"
         if ! test -e "$PEM" || [ "$(readlink "$PEM")" != "$CERT" ]
         then
      -    ln -sf "$CERT" "$PEM"
      +    ln -sf "${RELPATH}${CERT#$ROOT}" "$PEM"
           echo "+$PEM" >> "$ADDED"
         fi
         # Add trailing newline to certificate, if it is missing (#635570)
    GENTOO_CA_CERT_HEREDOC

    system 'patch -p1 -i ca-certificates-20150426-root.patch'

    system "sed -i 's,/usr/share/ca-certificates,#{CREW_PREFIX}/share/ca-certificates,g' \
      Makefile sbin/update-ca-certificates"
    system "sed -i 's,CERTSCONF=/etc/ca-certificates.conf,CERTSCONF=#{CREW_PREFIX}/etc/ca-certificates.conf,g' \
      sbin/update-ca-certificates"
    system "sed -i 's,ETCCERTSDIR=/etc/ssl/certs,ETCCERTSDIR=#{CREW_PREFIX}/etc/ssl/certs,g' \
      sbin/update-ca-certificates"
    system "sed -i 's,HOOKSDIR=/etc/ca-certificates/update.d,HOOKSDIR=#{CREW_PREFIX}/etc/ca-certificates/update.d,g' \
      sbin/update-ca-certificates"
    system "sed -i '/restorecon/d' sbin/update-ca-certificates"
    system "sed -i 's,/usr/sbin,#{CREW_PREFIX}/bin,g' sbin/Makefile"
  end

  def self.build
    system 'make'
  end

  def self.install
    FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/etc/ssl/certs/")
    FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/bin")
    FileUtils.mkdir_p("#{CREW_DEST_PREFIX}/share/ca-certificates/")
    system "make DESTDIR=#{CREW_DEST_DIR} install"

    File.write "#{CREW_DEST_PREFIX}/etc/ca-certificates.conf", <<~CA_CERT_CONF_HEREDOC
      # Automatically generated by Chromebrew package #{Module.nesting.first}
      # from ca-certificates-debian-#{version.split('-').first}
      # and from https://hg.mozilla.org/releases/mozilla-beta/rev/#{@mozilla_git_tag}
      # #{Time.now}
      # Do not edit.
    CA_CERT_CONF_HEREDOC

    File.write '08-ca-certificates', <<~CA_CERT_ENVD_HEREDOC
      # Set the ssl certificates path for ruby.
      SSL_CERT_DIR="${CREW_PREFIX}/etc/ssl/certs"
      SSL_CERT_FILE="${CREW_PREFIX}/etc/ssl/certs/ca-certificates.crt"
    CA_CERT_ENVD_HEREDOC
    FileUtils.install '08-ca-certificates', "#{CREW_DEST_PREFIX}/etc/env.d/08-ca-certificates", mode: 0o644

    system "sbin/update-ca-certificates --hooksdir '' --root #{CREW_DEST_DIR} --certsconf #{CREW_PREFIX}/etc/ca-certificates.conf"
    Dir.glob("#{CREW_DEST_PREFIX}/share/ca-certificates/mozilla/*.crt") do |cert_file|
      cert_basename = File.basename(cert_file, '.crt')
      FileUtils.ln_sf "#{CREW_PREFIX}/share/ca-certificates/mozilla/#{cert_basename}.crt",
                      "#{CREW_DEST_PREFIX}/etc/ssl/certs/#{cert_basename}.pem"
    end
    File.open("#{CREW_DEST_PREFIX}/etc/ssl/certs/ca-certificates.crt", 'a') do |mergedcerts|
      Dir["#{CREW_DEST_PREFIX}/share/ca-certificates/**/*.{crt}"] do |cert_file|
        File.foreach(cert_file) do |li|
          mergedcerts.write(li)
        end
      end
    end
    FileUtils.ln_sf "#{CREW_PREFIX}/etc/ssl/certs/ca-certificates.crt", "#{CREW_DEST_PREFIX}/etc/ssl/cert.pem"
  end
end
