require 'package'

class Gdk_base < Package
  description 'Set environment variables for autoscaling GTK applications'
  homepage 'https://gitlab.com/chromebrew/chromebrew/'
  version '1.0'
  license 'GPL-3'
  compatibility 'all'
  source_url 'SKIP'

  depends_on 'xdpyinfo'

  no_compile_needed

  def self.install
    gdk_base = <<~EOF
      # GDK environment variable settings

      # Do not edit this file. It will be overwritten by updates.

      SCALE=1
      RESOLUTION=$(xdpyinfo | awk '/dimensions:/ { print $2 }' | cut -d'x' -f1)
      [[ $RESOLUTION -gt 1500 && $RESOLUTION -lt 2500 ]] && SCALE=1.5
      [[ $RESOLUTION -ge 2500 && $RESOLUTION -lt 3500 ]] && SCALE=2
      [[ $RESOLUTION -ge 3500 && $RESOLUTION -lt 4500 ]] && SCALE=2.5
      [[ $RESOLUTION -ge 4500 && $RESOLUTION -lt 5500 ]] && SCALE=3
      [[ $RESOLUTION -gt 5500 ]] && SCALE=3.5
      [ -z "$DISPLAY" ] && DISPLAY=':0'
      export GDK_BACKEND=x11
      export GDK_SCALE=$SCALE
      export QT_SCALE_FACTOR=$SCALE
      export DISPLAY=$DISPLAY
    EOF
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/etc/env.d"
    File.write("#{CREW_DEST_PREFIX}/etc/env.d/09-gdk_base", gdk_base)
  end
end
