require 'package'

class Giflib < Package
  description 'giflib is a library for reading and writing gif images.'
  homepage 'https://giflib.sourceforge.net/'
  version '6.1.3'
  license 'MIT'
  compatibility 'aarch64 armv7l x86_64'
  source_url "https://downloads.sourceforge.net/project/giflib/giflib-#{version.split('.')[0]}.x/giflib-#{version}.tar.gz"
  source_sha256 'b65b66b99f0424b93525f987386f22fc5efb9da2bfc92ad4a532249aaffbab0e'
  binary_compression 'tar.zst'

  binary_sha256({
    aarch64: '524b6919b04736d4b72612cd27e5791dc67977f152984da2d39cc97dec9b718d',
     armv7l: '524b6919b04736d4b72612cd27e5791dc67977f152984da2d39cc97dec9b718d',
     x86_64: '300bdee898955cfc57d005a610f25e5b0611e941b104c04800fe2103424be8bb'
  })

  depends_on 'glibc' => :library
  depends_on 'glibc_lib' => :library
  depends_on 'imagemagick7' => :build

  no_env_options

  def self.patch
    # Fix /usr/local/bin/ld: fatal error: -soname: must take a non-empty argument
    system "sed -i 's/-soname -Wl,/-soname /g' Makefile"
    # Make sure all the binaries are installed
    system "sed -i 's/$(INSTALL) $^/$(INSTALL) $(UTILS)/' Makefile"
  end

  def self.build
    # No configure script in the source.
    system "#{CREW_ENV_OPTIONS.gsub('-mfpu=vfpv3-d16',
                                    '-mfpu=neon-fp16')} make PREFIX=#{CREW_PREFIX} LIBDIR=#{CREW_LIB_PREFIX}"
  end

  def self.check
    system 'make', 'check'
  end

  def self.install
    system 'make', "DESTDIR=#{CREW_DEST_DIR}", "PREFIX=#{CREW_PREFIX}", "LIBDIR=#{CREW_LIB_PREFIX}", 'MANUAL_PAGES=doc/*.1', 'install'
    # Remove static library.
    FileUtils.rm "#{CREW_DEST_LIB_PREFIX}/libgif.a"
    @libname = name.to_s.start_with?('lib') ? name.downcase : "lib#{name.gsub('lib', '').downcase}"
    @libnames = Dir["#{CREW_DEST_LIB_PREFIX}/#{@libname}.so*"]
    @libnames = Dir["#{CREW_DEST_LIB_PREFIX}/#{@libname}-*.so*"] if @libnames.empty?
    @libnames.each do |s|
      s.gsub!("#{CREW_DEST_LIB_PREFIX}/", '')
    end
    @dlname = @libnames.grep(/.so./).first
    @libname = @dlname.gsub(/.so.\d+/, '')
    @longest_libname = @libnames.max_by(&:length)
    @libvars = @longest_libname.rpartition('.so.')[2].split('.')
    @libtool_file = <<~LIBTOOLEOF
      # #{@libname}.la - a libtool library file
      # Generated by libtool (GNU libtool) (Created by Chromebrew)
      #
      # Please DO NOT delete this file!
      # It is necessary for linking the library.

      # The name that we can dlopen(3).
      dlname='#{@dlname}'

      # Names of this library.
      library_names='#{@libnames.reverse.join(' ')}'

      # The name of the static archive.
      old_library='#{@libname}.a'

      # Linker flags that cannot go in dependency_libs.
      inherited_linker_flags=''

      # Libraries that this one depends upon.
      dependency_libs=''

      # Names of additional weak libraries provided by this library
      weak_library_names=''

      # Version information for #{name}.
      current=#{@libvars[1]}
      age=#{@libvars[1]}
      revision=#{@libvars[2]}

      # Is this an already installed library?
      installed=yes

      # Should we warn about portability when linking against -modules?
      shouldnotlink=no

      # Files to dlopen/dlpreopen
      dlopen=''
      dlpreopen=''

      # Directory that this library needs to be installed in:
      libdir='#{CREW_LIB_PREFIX}'
    LIBTOOLEOF
    File.write("#{CREW_DEST_LIB_PREFIX}/#{@libname}.la", @libtool_file)
  end
end
