require 'package'

class Glibc < Package
  description 'The GNU C Library project provides the core libraries for GNU/Linux systems.'
  homepage 'https://www.gnu.org/software/libc/'
  version '2.41-4'
  license 'LGPL-2.1+, BSD, HPND, ISC, inner-net, rc, and PCRE'
  compatibility 'all'
  source_url "https://ftpmirror.gnu.org/glibc/glibc-#{version.partition('-')[0]}.tar.xz"
  source_sha256 'a5a26b22f545d6b7d7b3dd828e11e428f24f4fac43c934fb071b6a7d0828e901'
  binary_compression 'tar.zst'

  binary_sha256({
    aarch64: '4f76c7f82ad0dcf4e31ea3a8a8904228600eeffbf0c4444b06a8460cf33ff859',
     armv7l: '4f76c7f82ad0dcf4e31ea3a8a8904228600eeffbf0c4444b06a8460cf33ff859',
       i686: '9191a782dce9f5600dc9145e1beb0e0de9c1aca583ab7ddcbedd72b83b454b67',
     x86_64: '2ad34bffe4dae0bea47e1ae0a3ca36e48babf91cc152efc88f9ed72a988029a7'
  })

  depends_on 'gawk'    => :build
  depends_on 'libidn2' => :build
  depends_on 'texinfo' => :build
  depends_on 'libxcrypt' # Latest glibc removed libcrypt.so, add this for backward compatibility

  conflicts_ok
  no_env_options
  no_shrink
  print_source_bashrc

  def self.patch
    system "git clone --depth=1 https://github.com/chromebrew/crew-package-glibc"
    system 'filefix'

    Dir.glob('crew-package-glibc/patches/*.patch') do |patch|
      puts "Applying #{patch}...".yellow
      system 'patch', '-p1', '-i', patch
    end
  end

  def self.build
    cc_macro_list = %W[
      -DCREW_PREFIX=\\"#{CREW_PREFIX}\\"
      -DCREW_GLIBC_PREFIX=\\"#{CREW_GLIBC_PREFIX}\\"
      -DCREW_GLIBC_INTERPRETER=\\"#{CREW_GLIBC_INTERPRETER}\\"
      -DCREW_LD_LIBRARY_PATH=\\"#{CREW_GLIBC_PREFIX}:#{ENV.fetch('LD_LIBRARY_PATH', nil)}\\"
      -DSYSTEM_GLIBC_INTERPRETER=\\"/#{ARCH_LIB}/#{File.basename(CREW_GLIBC_INTERPRETER)}\\"
    ]

    build_env = {
      CFLAGS:   "-O3 -pipe -fPIC -fno-lto #{cc_macro_list.join(' ')}",
      CXXFLAGS: "-O3 -pipe -fPIC -fno-lto #{cc_macro_list.join(' ')}",
      LDFLAGS:  '-fno-lto'
    }

    config_opts = %W[
      --prefix=#{CREW_PREFIX}
      --libdir=#{CREW_GLIBC_PREFIX}
      --mandir=#{CREW_MAN_PREFIX}
      --with-headers=#{CREW_PREFIX}/include
      --with-bugurl=https://github.com/chromebrew/chromebrew/issues/new
      --enable-bind-now
      --enable-fortify-source
      --enable-kernel=3.2
      --enable-shared
      --disable-nscd
      --disable-multilib
      --disable-profile
      --disable-sanity-checks
      --disable-werror
      --without-cvs
      --without-selinux
    ]

    config_opts << '--enable-cet' unless ARCH == 'i686'

    FileUtils.mkdir_p %w[builddir]

    Dir.chdir('builddir') do
      File.write 'configparms', <<~EOF
        slibdir=#{CREW_GLIBC_PREFIX}
        rtlddir=#{CREW_GLIBC_PREFIX}
        sbindir=#{CREW_PREFIX}/bin
        rootsbindir=#{CREW_PREFIX}/bin
      EOF

      system build_env.transform_keys(&:to_s), '../configure', *config_opts, no_preload_hacks: true
      system "make PARALLELMFLAGS='-j #{CREW_NPROC}'", no_preload_hacks: true
    end

    build_flags = "-B #{CREW_GLIBC_PREFIX} -L #{CREW_GLIBC_PREFIX} #{ARCH.eql?('x86_64') ? '-m64' : '-m32'}"

    system <<~CMD, chdir: 'crew-package-glibc/crew-preload', no_preload_hacks: true
      cc #{CREW_COMMON_FLAGS} #{build_flags} -shared -lc -ldl \
        -include compat-header/glibc-2.23-#{ARCH}.h \
        -Wl,--allow-multiple-definition main.c hooks.c \
        -o ../crew-preload.so
    CMD
  end

  def self.install
    FileUtils.mkdir_p %W[#{CREW_DEST_PREFIX}/etc/env.d #{CREW_DEST_PREFIX}/etc/ld.so.conf.d #{CREW_DEST_LIB_PREFIX}]

    system "make DESTDIR=#{CREW_DEST_DIR} install", chdir: 'builddir'
    system "make DESTDIR=#{CREW_DEST_DIR} localedata/install-locales", chdir: 'builddir'

    # create symlinks for static libraries/objects in CREW_LIB_PREFIX
    Dir.glob("#{CREW_DEST_DIR}#{CREW_GLIBC_PREFIX}/*.{a,o}") do |f|
      filename = File.basename(f)
      FileUtils.ln_s "../opt/glibc-libs/#{filename}", "#{CREW_DEST_LIB_PREFIX}/#{filename}"
    end

    File.write "#{CREW_DEST_PREFIX}/etc/ld.so.conf", <<~EOF
      # ld.so.conf autogenerated by Chromebrew
      # DO NOT put your changes here. Instead, put them in
      # #{CREW_PREFIX}/etc/ld.so.conf.d/ instead.

      include #{CREW_PREFIX}/etc/ld.so.conf.d/*.conf
      #{CREW_GLIBC_PREFIX}
      #{CREW_LIB_PREFIX}
      include /etc/ld.so.conf
    EOF

    # install crew-audit
    FileUtils.install 'crew-package-glibc/crew-preload.so', File.join(CREW_DEST_LIB_PREFIX, 'crew-preload.so'), mode: 0o755
    File.write "#{CREW_DEST_PREFIX}/etc/env.d/10-glibc", "LD_PRELOAD=#{File.join(CREW_LIB_PREFIX, 'crew-preload.so')}\n"
  end

  def self.postinstall
    # update search cache for ld.so
    system "#{CREW_PREFIX}/bin/ldconfig", %i[out err] => File::NULL
  end
end
