require 'package'

class Py3_codespell < Package
  description 'Fix common misspellings in text files.'
  homepage 'https://github.com/codespell-project/codespell'
  @_ver = '2.2.2'
  version @_ver
  license 'GPL-2.0'
  compatibility 'all'
  source_url 'https://github.com/codespell-project/codespell.git'
  git_hashtag "v#{@_ver}"

  binary_url({
    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/py3_codespell/2.2.2_armv7l/py3_codespell-2.2.2-chromeos-armv7l.tar.zst',
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/py3_codespell/2.2.2_armv7l/py3_codespell-2.2.2-chromeos-armv7l.tar.zst',
       i686: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/py3_codespell/2.2.2_i686/py3_codespell-2.2.2-chromeos-i686.tar.zst',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/py3_codespell/2.2.2_x86_64/py3_codespell-2.2.2-chromeos-x86_64.tar.zst'
  })
  binary_sha256({
    aarch64: '9ca45977571e7288423e2eaa641365ff3ed249ce04725b4d1ffbcf8863b87f31',
     armv7l: '9ca45977571e7288423e2eaa641365ff3ed249ce04725b4d1ffbcf8863b87f31',
       i686: 'ee404a4b53183744a0102827f34c43f7b06e4ccd2ef11565b8c160a953865d9a',
     x86_64: '1f2e5d809b529d6934686e7e2af476dd066f224896f2b5f0efde061e2e5fba37'
  })

  depends_on 'py3_setuptools' => :build

  python_major = `python3 -V | cut -d' ' -f2 | cut -d'.' -f1`.chomp
  python_minor = `python3 -V | cut -d' ' -f2 | cut -d'.' -f2`.chomp
  @python_ver = "python#{python_major}.#{python_minor}"

  def self.build
    system "python3 setup.py build #{PY3_SETUP_BUILD_OPTIONS}"
  end

  def self.install
    system "python3 setup.py install #{PY_SETUP_INSTALL_OPTIONS}"
    # Fixes ModuleNotFoundError: No module named 'codespell_lib._version'
    _version_tuple = "(#{@_ver.gsub('.', ', ')})"
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/lib/#{@python_ver}/site-packages/codespell_lib"
    _version = <<~EOF
      # coding: utf-8
      # file generated by setuptools_scm
      # don't change, don't track in version control
      __version__ = version = '#{@_ver}'
      __version_tuple__ = version_tuple = #{_version_tuple}
    EOF
    File.write("#{CREW_DEST_PREFIX}/lib/#{@python_ver}/site-packages/codespell_lib/_version.py", _version)
  end

  def self.remove
    # Remove data, __pycache__ and tests directories.
    FileUtils.rm_rf "#{CREW_PREFIX}/lib/#{@python_ver}/site-packages/codespell_lib"
  end
end
