---
name: ActionLint
on: workflow_call
env:
  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.CREW_PR_TOKEN }}
  GH_TOKEN: ${{ secrets.CREW_PR_TOKEN }}
  REVIEWDOG_TOKEN: ${{ secrets.CREW_PR_TOKEN }}
  SHELLCHECK_OPTS: "-e SC2129"
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          fail_level: none
          reporter: github-pr-review
