---
name: autocheck
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write
  repository-projects: read
jobs:
  autocheck:
    if: ${{ github.repository_owner == 'chromebrew' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Get GH Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: chromebrew
      - name: Run required checks if necessary
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
            for pr in $(gh pr list -s open --author app/github-actions --json number | jq '.[].number')
            do
              # Run check workflow if it didn't already run.
              gh pr checks --required $pr || (echo "Running check workflow on PR ${pr}." ; gh workflow run Unit-Test.yml $pr)
              # Add reviewers to autogenerated PRs.
              gh pr edit $pr --add-reviewer chromebrew/active
            done
