---
# Version 1.0
name: autocheck
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CREW_PR_TOKEN }}
permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write
  repository-projects: read
jobs:
  autocheck:
    if: ${{ github.repository_owner == 'chromebrew' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - name: Run required checks if necessary
        run: |
            for pr in $(gh pr list -s open --author app/github-actions --json number | jq '.[].number')
            do
              PR_BRANCH="$(gh pr list -s open --author app/github-actions --json headRefName,number | jq --arg PR_NUMBER ${pr} -e -r '.[]|select(.number == '$PR_NUMBER')|.headRefName')"
              # Run check workflow if it didn't already run.
              gh pr checks --required $pr || (
                echo "Running check workflow on PR ${pr}."
                gh workflow run Unit-Test.yml -f branch="${PR_BRANCH}"
                )
              # Add reviewers to autogenerated PRs.
              gh workflow run Set-Reviewers.yml -R ${{ github.repository }} -f branch="${PR_BRANCH}"
            done
