---
name: Generate Updates for Core and Buildessential Packages.
on:
  schedule:
    - cron: '0 8 * * *'  # Daily
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CREW_PR_TOKEN }}  # setting GH_TOKEN for the entire workflow
permissions:                    # Global permissions configuration starts here
  actions: write
  contents: write
  packages: write
  pull-requests: write          # 'write' access to pull requests
jobs:
  update-check:
    if: ${{ github.repository_owner == 'chromebrew' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: true
      - name: Check for updates in core and buildessential packages.
        id: trigger-update-checks
        run: |
          # shellcheck disable=SC2116
          gh workflow -R chromebrew/chromebrew run Package-Dependencies-Updater.yml -f version_cmd_input="core buildessential"
